// packages/svelte/src/client/Link.svelte
<script>
  /**
   * Specifies the URL of the linked resource.
   *
   * @type {VesselRoutes[keyof VesselRoutes]}
   */
  export let href;
  /**
   * Whether this route should begin prefetching if the user is about to interact with the link.
   *
   * @type {boolean}
   * @defaultValue true
   */
  export let prefetch = true;
  /**
   * Replace the current history instead of pushing a new URL on to the stack.
   *
   * @type {boolean}
   * @defaultValue false
   */
  export let replace = false;
</script>

<a
  {href}
  {...$$restProps}
  data-prefetch={prefetch ? '' : null}
  data-replace={replace ? '' : null}
>
  <slot />
</a>

// packages/solid/src/client/Link.tsx
import type { ParentComponent } from 'solid-js';

export interface LinkProps {
  /**
   * Specifies the URL of the linked resource.
   */
  href: VesselRoutes[keyof VesselRoutes] | URL;
  /**
   * Whether this route should begin prefetching if the user is about to interact with the link.
   *
   * @defaultValue true
   */
  prefetch?: boolean;
  /**
   * Replace the current history instead of pushing a new URL on to the stack.
   *
   * @defaultValue false
   */
  replace?: boolean;
}

const Link: ParentComponent<LinkProps> = (props) => {
  return (
    <a
      {...props}
      href={props.href instanceof URL ? props.href.href : props.href}
      data-prefetch={props.prefetch !== false ? '' : null}
      data-replace={props.replace ? '' : null}
    >
      {props.children}
    </a>
  );
};

export default Link;
