// packages/svelte/src/client/RouteSegment.svelte
<script>
  import { setContext } from 'svelte';
  import { writable } from 'svelte/store';

  import { ROUTE_PARAMS_KEY } from './context-keys';
  import RouteComponent from './RouteComponent.svelte';
  import RouteErrorBoundary from './ErrorBoundary';

  export let matches;
  export let depth;

  $: match = matches[depth];

  const routeParams = writable();
  setContext(ROUTE_PARAMS_KEY, routeParams);
  $: routeParams.set(match.params);
</script>

<RouteComponent component={match.layout}>
  <RouteErrorBoundary error={match.error} boundary={match.errorBoundary}>
    {#if depth < matches.length - 1}
      <svelte:self {matches} depth={depth + 1} />
    {:else}
      <RouteComponent component={match.page} leaf />
    {/if}
  </RouteErrorBoundary>
</RouteComponent>

// packages/solid/src/client/RouteSegment.tsx
import { type ClientLoadedRoute } from '@vessel-js/app';
import { type ParentComponent } from 'solid-js';

import { useVesselContext } from './context';
import { ROUTE_PARAMS_KEY } from './context-keys';
import RouteComponent from './RouteComponent';
import RouteErrorBoundary from './RouteErrorBoundary';

type RouteSegmentProps = {
  matches: ClientLoadedRoute[];
  depth: number;
};

const RouteSegment: ParentComponent<RouteSegmentProps> = (props) => {
  const match = () => props.matches[props.depth];
  const params = () => match().params;

  const context = useVesselContext();
  context.set(ROUTE_PARAMS_KEY, params);

  return (
    <RouteComponent component={match().layout}>
      <RouteErrorBoundary error={match().error} boundary={match().errorBoundary}>
        {props.depth < props.matches.length - 1 ? (
          <RouteSegment matches={props.matches} depth={props.depth + 1} />
        ) : (
          <RouteComponent component={match().page} leaf />
        )}
      </RouteErrorBoundary>
    </RouteComponent>
  );
};

export default RouteSegment;
