// packages/solid/src/client/RouteComponent.tsx
import { type ClientLoadedRoute } from '@vessel-js/app';
import {
  createComponent,
  createEffect,
  createMemo,
  createSignal,
  type ParentComponent,
} from 'solid-js';

import { useVesselContext } from './context';
import { SERVER_DATA_KEY, SERVER_ERROR_KEY, STATIC_DATA_KEY } from './context-keys';

type RouteProps = {
  component?: ClientLoadedRoute['page'];
  leaf?: boolean;
};

const RouteComponent: ParentComponent<RouteProps> = (props) => {
  const context = useVesselContext();

  const resolveStaticData = () => props.component?.staticData ?? {};
  const resolveServerData = () => props.component?.serverData;
  const resolveServerError = () => props.component?.serverLoadError;

  const [staticData, setStaticData] = createSignal(resolveStaticData());
  const [serverData, setServerData] = createSignal(resolveServerData());
  const [serverError, setServerError] = createSignal(resolveServerError());

  context.set(STATIC_DATA_KEY, staticData);
  context.set(SERVER_DATA_KEY, serverData);
  context.set(SERVER_ERROR_KEY, serverError);

  createEffect(() => {
    setStaticData(resolveStaticData());
    setServerData(resolveServerData());
    setServerError(resolveServerError());
  });

  return createMemo(() =>
    props.component
      ? createComponent(props.component.module.default, {
          children: !props.leaf ? props.children : null,
        })
      : !props.leaf && props.children,
  );
};

export default RouteComponent;

// packages/svelte/src/client/RouteComponent.svelte
<script>
  import { setContext } from 'svelte';
  import { writable } from 'svelte/store';

  import {
    SERVER_DATA_KEY,
    SERVER_ERROR_KEY,
    STATIC_DATA_KEY,
  } from './context-keys';

  export let component;
  export let leaf = false;

  const staticData = writable({}),
    serverData = writable(),
    serverError = writable();

  setContext(STATIC_DATA_KEY, staticData);
  setContext(SERVER_DATA_KEY, serverData);
  setContext(SERVER_ERROR_KEY, serverError);

  $: staticData.set(component?.staticData ?? {});
  $: serverData.set(component?.serverData);
  $: serverError.set(component?.serverLoadError);
</script>

{#if component}
  {#if !leaf}
    <svelte:component this={component.module.default}>
      <slot />
    </svelte:component>
  {:else}
    <svelte:component this={component.module.default} />
  {/if}
{:else if !leaf}
  <slot />
{/if}
